const DESTINOS = [
    {
        
        id: 'kljaso1',
        title: 'Alico Pira',
        location: 'Piracicaba',
        country: 'Brasil',
        countryFlagUrl: '/assets/flag_brasil.png',
        pictureUrl: '/assets/Amazon Roosevelt 6_img.png',
    },
    {
        id: 'asmdas',
        title: 'Alico Pira',
        location: 'Recife',
        country: 'Brasil',
        countryFlagUrl: '/assets/flag_brasil.png',
        pictureUrl: '/assets/Amazon Roosevelt 6_img.png',
    },
    {
        id: '12d1das',
        title: 'Recife Tarpon',
        location: 'Piracicaba',
        country: 'Argentina',
        countryFlagUrl: '/assets/flag_argentina.jpeg',
        pictureUrl: '/assets/Amazon Roosevelt 3recife_tarpon.png',
    },
    {
        id: 'nas981',
        title: 'Aldea Tzunun',
        location: 'Calle Polar Poniente',
        country: 'México',
        countryFlagUrl: '/assets/flag_mexico.png',
        pictureUrl: '/assets/Amazon Roosevelt 3recife_tarpon.png',
    },
    {
        id: '1231k23mc',
        title: 'Alico Pira',
        location: 'Piracicaba',
        country: 'Brasil',
        countryFlagUrl: '/assets/flag_brasil.png',
        pictureUrl: '/assets/Amazon Roosevelt 6_img.png',
    },
    {
        id: 'k1oc23c12',
        title: 'Recife Tarpon',
        location: 'Piracicaba',
        country: 'Argentina',
        countryFlagUrl: '/assets/flag_argentina.jpeg',
        pictureUrl: '/assets/Amazon Roosevelt 3recife_tarpon.png',
    },
    {
        id: 'adjo12',
        title: 'Recife Tarpon',
        location: 'Piracicaba',
        country: 'Argentina',
        countryFlagUrl: '/assets/flag_argentina.jpeg',
        pictureUrl: '/assets/Amazon Roosevelt 3recife_tarpon.png',
    },
    {
        
        id: 'z9s0asd',
        title: 'Alico Pira',
        location: 'Piracicaba',
        country: 'Brasil',
        countryFlagUrl: '/assets/flag_brasil.png',
        pictureUrl: '/assets/Amazon Roosevelt 6_img.png',
    },
    {
        id: 'qweoko12e',
        title: 'Alico Pira',
        location: 'Recife',
        country: 'Brasil',
        countryFlagUrl: '/assets/flag_brasil.png',
        pictureUrl: '/assets/Amazon Roosevelt 6_img.png',
    },
    {
        id: 'mqiweu12e1',
        title: 'Recife Tarpon',
        location: 'Piracicaba',
        country: 'Argentina',
        countryFlagUrl: '/assets/flag_argentina.jpeg',
        pictureUrl: '/assets/Amazon Roosevelt 3recife_tarpon.png',
    },
    {
        id: '12ok39c1',
        title: 'Aldea Tzunun',
        location: 'Calle Polar Poniente',
        country: 'México',
        countryFlagUrl: '/assets/flag_mexico.png',
        pictureUrl: '/assets/Amazon Roosevelt 3recife_tarpon.png',
    },
    {
        id: 'c-0102c1-m',
        title: 'Alico Pira',
        location: 'Piracicaba',
        country: 'Brasil',
        countryFlagUrl: '/assets/flag_brasil.png',
        pictureUrl: '/assets/Amazon Roosevelt 6_img.png',
    },
    {
        id: '1ck2o1c210c1',
        title: 'Recife Tarpon',
        location: 'Piracicaba',
        country: 'Argentina',
        countryFlagUrl: '/assets/flag_argentina.jpeg',
        pictureUrl: '/assets/Amazon Roosevelt 3recife_tarpon.png',
    },
    {
        id: 'i12031c20c1',
        title: 'Recife Tarpon',
        location: 'Piracicaba',
        country: 'Argentina',
        countryFlagUrl: '/assets/flag_argentina.jpeg',
        pictureUrl: '/assets/Amazon Roosevelt 3recife_tarpon.png',
    },
    {
        id: 'anidi      ',
        title: 'Alico Pira',
        location: 'Recife',
        country: 'Brasil',
        countryFlagUrl: '/assets/flag_brasil.png',
        pictureUrl: '/assets/Amazon Roosevelt 6_img.png',
    },
    {
        id: '  dasj q  w   q2 qw',
        title: 'Recife Tarpon',
        location: 'Piracicaba',
        country: 'Argentina',
        countryFlagUrl: '/assets/flag_argentina.jpeg',
        pictureUrl: '/assets/Amazon Roosevelt 3recife_tarpon.png',
    },
    {
        id: 'amsd 90902',
        title: 'Aldea Tzunun',
        location: 'Calle Polar Poniente',
        country: 'México',
        countryFlagUrl: '/assets/flag_mexico.png',
        pictureUrl: '/assets/Amazon Roosevelt 3recife_tarpon.png',
    },
    {
        id: 'c2891912',
        title: 'Alico Pira',
        location: 'Piracicaba',
        country: 'Brasil',
        countryFlagUrl: '/assets/flag_brasil.png',
        pictureUrl: '/assets/Amazon Roosevelt 6_img.png',
    },
    {
        id: 'k123123',
        title: 'Recife Tarpon',
        location: 'Piracicaba',
        country: 'Argentina',
        countryFlagUrl: '/assets/flag_argentina.jpeg',
        pictureUrl: '/assets/Amazon Roosevelt 3recife_tarpon.png',
    },
    {
        id: 'adjo1122',
        title: 'Recife Tarpon',
        location: 'Piracicaba',
        country: 'Argentina',
        countryFlagUrl: '/assets/flag_argentina.jpeg',
        pictureUrl: '/assets/Amazon Roosevelt 3recife_tarpon.png',
    },
    {
        
        id: 'z9s0a3440sd',
        title: 'Alico Pira',
        location: 'Piracicaba',
        country: 'Brasil',
        countryFlagUrl: '/assets/flag_brasil.png',
        pictureUrl: '/assets/Amazon Roosevelt 6_img.png',
    },
    {
        id: 'qweoko42112e',
        title: 'Alico Pira',
        location: 'Recife',
        country: 'Brasil',
        countryFlagUrl: '/assets/flag_brasil.png',
        pictureUrl: '/assets/Amazon Roosevelt 6_img.png',
    },
    {
        id: 'mqiwe1312u12e1',
        title: 'Recife Tarpon',
        location: 'Piracicaba',
        country: 'Argentina',
        countryFlagUrl: '/assets/flag_argentina.jpeg',
        pictureUrl: '/assets/Amazon Roosevelt 3recife_tarpon.png',
    },
    {
        id: '12ok39c1312312',
        title: 'Aldea Tzunun',
        location: 'Calle Polar Poniente',
        country: 'México',
        countryFlagUrl: '/assets/flag_mexico.png',
        pictureUrl: '/assets/Amazon Roosevelt 3recife_tarpon.png',
    },
    {
        id: 'c-0102c1-12312331m',
        title: 'Alico Pira',
        location: 'Piracicaba',
        country: 'Brasil',
        countryFlagUrl: '/assets/flag_brasil.png',
        pictureUrl: '/assets/Amazon Roosevelt 6_img.png',
    },
    {
        id: '1ck2o1c210c1412',
        title: 'Recife Tarpon',
        location: 'Piracicaba',
        country: 'Argentina',
        countryFlagUrl: '/assets/flag_argentina.jpeg',
        pictureUrl: '/assets/Amazon Roosevelt 3recife_tarpon.png',
    },
    {
        id: 'i12031c20242341c1',
        title: 'Recife Tarpon',
        location: 'Piracicaba',
        country: 'Argentina',
        countryFlagUrl: '/assets/flag_argentina.jpeg',
        pictureUrl: '/assets/Amazon Roosevelt 3recife_tarpon.png',
    },

];


export default DESTINOS;